[workspace]
members = ["rpc-gateway-config", "rpc-gateway-core"]

[package]
name = "rpc-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
alloy-chains = "0.1"
alloy-json-rpc = "0.13.0"
moka = { version = "0.12.10", features = ["future"] }
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["json"] }
rpc-gateway-config = { path = "./rpc-gateway-config" }
rpc-gateway-core = { path = "./rpc-gateway-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8"
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = "2.5"
