server:
  host: "0.0.0.0"
  port: 8080

load_balancing:
  strategy: "primary_only"

error_handling:
  type: "retry"
  max_retries: 3
  retry_delay: "1s"
  jitter: true

cache:
  type: "redis"
  url: "redis://redis:6379"

metrics:
  host: "0.0.0.0"
  port: 8082

logging:
  console:
    enabled: true
    rust_log: "debug"
    format: "text"
    include_target: true
    include_thread_ids: true
    include_thread_names: true
    include_file: true
    include_line_number: true
  file:
    enabled: false
    rust_log: "info"
    format: "json"
    path: "logs/rpc-gateway.log"
    rotation: "daily"
    include_target: true
    include_thread_ids: true
    include_thread_names: true
    include_file: true
    include_line_number: true

chains:
  1: # Ethereum Mainnet
    # block_time: 12000
    upstreams:
      - url: "http://mainnet:8545"
        timeout: "10s"
        weight: 1

  137: # Polygon
    # block_time: 12000
    upstreams:
      - url: "http://polygon:8545"
        timeout: "10s"
        weight: 1

  42161: # Arbitrum
    # block_time: 12000
    upstreams:
      - url: "http://arbitrum:8545"
        timeout: "10s"
        weight: 1
