# Docker Compose configuration for local development

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./docker.config.yml:/etc/rpc-gateway/config.yml
    depends_on:
      - redis
      - mainnet
      - polygon
      - arbitrum
  # Ethereum Mainnet (Chain ID 1) node

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

  mainnet:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-mainnet
    ports:
      - "8545:8545"
    entrypoint:
      [
        "anvil",
        "--chain-id",
        "1",
        "--block-time",
        "12",
        "--host",
        "0.0.0.0",
        "--port",
        "8545",
      ]
    healthcheck:
      # send eth_getBlockNumber
      test:
        [
          "CMD",
          "curl",
          "-X",
          "POST",
          "-H",
          "Content-Type: application/json",
          "--data",
          '{"jsonrpc":"2.0","method":"eth_getBlockNumber","params":[],"id":1}',
          "http://localhost:8545",
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  # Polygon (Chain ID 137) node
  polygon:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-polygon
    ports:
      - "8546:8545"
    entrypoint:
      [
        "anvil",
        "--chain-id",
        "137",
        "--block-time",
        "2",
        "--host",
        "0.0.0.0",
        "--port",
        "8545",
      ]
    healthcheck:
      # send eth_getBlockNumber
      test:
        [
          "CMD",
          "curl",
          "-X",
          "POST",
          "-H",
          "Content-Type: application/json",
          "--data",
          '{"jsonrpc":"2.0","method":"eth_getBlockNumber","params":[],"id":1}',
          "http://localhost:8545",
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  # Arbitrum (Chain ID 42161) node
  arbitrum:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-arbitrum
    ports:
      - "8547:8545"
    entrypoint:
      [
        "anvil",
        "--chain-id",
        "42161",
        "--block-time",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "8545",
      ]
    healthcheck:
      # send eth_getBlockNumber
      test:
        [
          "CMD",
          "curl",
          "-X",
          "POST",
          "-H",
          "Content-Type: application/json",
          "--data",
          '{"jsonrpc":"2.0","method":"eth_getBlockNumber","params":[],"id":1}',
          "http://localhost:8545",
        ]
      interval: 10s
      timeout: 5s
      retries: 2
