server:
  host: "127.0.0.1"
  port: 8080

proxy:
  forward_headers:
    - Origin

cors:
  allow_any_origin: true

load_balancing:
  strategy: "primary_only"

request_coalescing:
  enabled: true
  # method_filter:
  #   type: "whitelist"
  #   methods:
  #     - eth_call
  #     - eth_getTransactionCount
  #     - eth_getBalance
  #     - eth_getBlockByNumber
  #     - eth_getBlockByHash

upstream_health_checks:
  enabled: true
  interval: "5m"

metrics:
  enabled: true
  host: "0.0.0.0"
  port: 8082

# error_handling:
# type: "retry"
# max_retries: 3
# retry_delay: "1s"
# jitter: true

cache:
  # type: "disabled"
  type: "local"
  capacity: 10000

logging:
  console:
    enabled: true
    # rust_log: "warn,rpc_gateway_core=info"
    rust_log: "info"
    format: "text"
    include_target: true
    include_thread_ids: true
    include_thread_names: true
    include_file: true
    include_line_number: true
  file:
    # enabled: true
    enabled: false
    # rust_log: "debug,rpc_gateway=debug,actix_server=error,actix_web=error,tracing_actix_web=error,redis=error,tokio=error"
    format: "json"
    path: "logs/rpc-gateway.log"
  #   rotation: "daily"
  #   include_target: true
  #   include_thread_ids: true
  #   include_thread_names: true
  #   include_file: true
  #   include_line_number: true

projects:
  - name: "nodes"

  - name: "web-app"
    key: "$WEB_APP_KEY"

  - name: "loadtest"

chains:
  1:
    upstreams:
      - url: "$ALCHEMY_ETH_MAINNET_URL"
        timeout: "10s"
        weight: 1
  8453:
    upstreams:
      - url: "$ALCHEMY_BASE_MAINNET_URL"
        timeout: "10s"
        weight: 1
      # - url: "$INFURA_URL"
      #   timeout: "10s"
      #   weight: 2

  84532:
    upstreams:
      - url: "$ALCHEMY_BASE_SEPOLIA_URL"
        timeout: "10s"
        weight: 1
