[server]
host = "127.0.0.1"
port = 9090

[load_balancing]
type = "weighted_round_robin"
weight_decay = 0.5

[error_handling]
type = "retry"
max_retries = 3
retry_delay = "1s"
jitter = true

[chains.1]
upstreams = [
  { url = "$ALCHEMY_URL", timeout = "10s", weight = 1 },
  { url = "$INFURA_URL", timeout = "10s", weight = 2 },
]
