server:
  host: "127.0.0.1"
  port: 8080

cors:
  allow_any_origin: true

load_balancing:
  strategy: "primary_only"

# request_coalescing:
#   enabled: false
#   # timeout: "block_time"
#   # ttl: "block_time"

upstream_health_checks:
  enabled: true
  interval: "5m"

metrics:
  enabled: true
  host: "0.0.0.0"
  port: 8082

# error_handling:
# type: "retry"
# max_retries: 3
# retry_delay: "1s"
# jitter: true

cache:
  # type: "disabled"
  type: "local"
  capacity: 10000

logging:
  console:
    enabled: true
    # rust_log: "debug,rpc_gateway=debug,actix_server=error,actix_web=error,tracing_actix_web=error,redis=error,tokio=error"
    format: "text"
    include_target: true
    include_thread_ids: true
    include_thread_names: true
    include_file: true
    include_line_number: true
  file:
    enabled: true
    # rust_log: "debug,rpc_gateway=debug,actix_server=error,actix_web=error,tracing_actix_web=error,redis=error,tokio=error"
    format: "json"
    path: "logs/rpc-gateway.log"
  #   rotation: "daily"
  #   include_target: true
  #   include_thread_ids: true
  #   include_thread_names: true
  #   include_file: true
  #   include_line_number: true

projects:
  - name: "nodes"

  - name: "web-app"
    key: "$WEB_APP_KEY"

chains:
  1:
    upstreams:
      - url: "$ALCHEMY_URL"
        timeout: "10s"
        weight: 1
      # - url: "$INFURA_URL"
      #   timeout: "10s"
      #   weight: 2
