[server]
host = "127.0.0.1"
port = 9090

[load_balancing]
type = "weighted_round_robin"
weight_decay = 0.5

[error_handling]
type = "retry"
max_retries = 3
retry_delay = "1s"
jitter = true

[logging.console]
enabled = true
level = "debug"
format = "text"
include_target = true
include_thread_ids = true
include_thread_names = true
include_file = true
include_line_number = true

[logging.file]
enabled = true
level = "info"
format = "json"
path = "logs/rpc-gateway.log"
rotation = "daily"
include_target = true
include_thread_ids = true
include_thread_names = true
include_file = true
include_line_number = true

[chains.1]
upstreams = [
  { url = "https://mainnet.infura.io/v3/YOUR_INFURA_API_KEY", timeout = "10s", weight = 1 },
  { url = "https://mainnet.alchemy.com/YOUR_ALCHEMY_API_KEY", timeout = "10s", weight = 2 },
]
