rpc-gateway:
  image:
    pullPolicy: Always
  config:
    server:
      port: 8080
      host: "0.0.0.0"

    cache:
      type: "redis"
      url: "redis://minikube-example-redis-master.default.svc.cluster.local:6379"

    logging:
      console:
        enabled: true
        level: debug
    chains:
      1:
        upstreams:
          - url: "$ALCHEMY_URL"
            timeout: "10s"
            weight: 1
          # - url: "$INFURA_URL"
          #   timeout: "10s"
          #   weight: 2
  env:
    - name: ALCHEMY_URL
      valueFrom:
        secretKeyRef:
          name: rpc-gateway-upstream-urls
          key: ALCHEMY_URL

redis:
  architecture: standalone

  auth:
    enabled: false

  master:
    persistence:
      enabled: false

    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"

  replica:
    replicaCount: 0

secrets:
  ALCHEMY_URL: "" # This will be set by the deployment command
