[package]
name = "rpc-gateway-config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
alloy-chains = { version = "0.1.69", features = ["serde"] }
toml = "0.8"
url = "2.5"
