apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpc-gateway.fullname" . }}-config
  labels: {{- include "rpc-gateway.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | nindent 4 -}} 