apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpc-gateway.fullname" . }}-config
  labels: {{- include "rpc-gateway.labels" . | nindent 4 }}
data:
  config.yml: |
    target: k8s
    {{ .Values.config | toYaml | nindent 4 -}}

