[package]
name = "rpc-gateway-core"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
actix-web.workspace = true
alloy-chains.workspace = true
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-dyn-abi.workspace = true
anvil-core.workspace = true
anvil-rpc.workspace = true
anvil-server.workspace = true
async-trait.workspace = true
arc-swap.workspace = true
duration-str.workspace = true
futures.workspace = true
moka.workspace = true
nonempty.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
redis = { version = "0.29.5", features = ["tokio-comp", "cluster-async"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-actix-web.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
clap.workspace = true
dashmap = "6.1.0"
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
quanta = "0.12.5"

[[bin]]
name = "rpc-gateway"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"

[profile.dev]
debug = true
split-debuginfo = "packed"
opt-level = 0
debug-assertions = true
overflow-checks = true
incremental = true
codegen-units = 256
